### PR TITLE
Support weakdeps

### PR DESCRIPTION
**Pull request by qiaojunfeng**
Hi, thanks for sharing the package!

Julia 1.9 introduces [package extension](https://pkgdocs.julialang.org/v1/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)), it seems Comonicon does not support this yet?

I just tried to come up with a quick hack, and it seems working fine in my case. Would be great if someone could have a look at this PR (maybe use this as a hint), and properly support this Julia feature in Comonicon. Thanks!

### CODE REVIEW

**Comment by Roger-luo** [comment]
Ah right, thanks! 

The building procedure uses a hack to create a build env based on your test and project env. Can you add a test project test to check if this works in the test suite? You can add a weakdeps in this example project https://github.com/comonicon/Comonicon.jl/tree/main/example/FakePkg

and you can modify the tests in that package.

**Comment by qiaojunfeng** [comment]
Ok, pushed another commit, this should fix the Julia 1.6 tests

**Comment by qiaojunfeng** [comment]
Ok pushed a fix for Julia 1.6 again, could you restart the CI? Thanks!

**Comment by qiaojunfeng** [comment]
I think the code is fine now, but it seems the coverage of `example` wasn't generated so the coverage tests didn't pass
```
[ Info: CoverageTools.process_file: Detecting coverage for src/builder/sysimg.jl
┌ Info: CoverageTools.process_cov: Coverage file(s) for src/builder/sysimg.jl do not exist.
└ Assuming file has no coverage.
```
from the `Run julia-actions/julia-processcoverage@v1` step of https://github.com/comonicon/Comonicon.jl/actions/runs/6111989250/job/16591892397

**Comment by Roger-luo** [comment]
Thanks fine it's not much, thanks!

**Pull request merged**
